name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
            node-version: '14'
      - name: run
        run: |
          npm -g install yarn
      - name: cache node_modules
      id: node_modules_cache_id
      uses: actions/cache@v2
      with:
        path: |
          node_modules
        key: node-v${{ matrix.node-version }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
      - name: Build
        run: |
          yarn honkit build . docs
      - name: Push to build branch
        uses: s0/git-publish-subdir-action@master
        env:
         REPO: self
         BRANCH: docs
         FOLDER: docs
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}